trigger:
- main

pool:
  name: Macpool

variables:
  serviceConnection: 'ACR-piprline'

  acrName: 'acrCloudDrove1254'

  imageRepository: 'nginx-docker'
  tag: 'v1'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildImage
    displayName: 'Build and Push'
    steps:
    - task: AzureCLI@2
      displayName: 'Build and Push to ACR'
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr build --registry $(acrName) --image $(imageRepository):$(tag) . -f docker/Dockerfile
        workingDirectory: '$(System.DefaultWorkingDirectory)'
