FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    unzip   \
    apt-transport-https \
    gnupg \
    software-properties-common
    

# Install Terraform
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    tee /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && \
    apt-get install -y terraform

# Install Azure CLI
RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null && \
    curl -sL https://packages.microsoft.com/config/ubuntu/20.04/azcli.list | tee /etc/apt/sources.list.d/azcli.list && \
    apt-get update && \
    apt-get install -y azcli

CMD ["bash"]